### ISSUE TITLE
Fix race conditions

### ISSUE THREAD

**Issue by jasonv75** [veltor/veltor-network#23]
Many parts of the network package currently use maps that are accessed concurrently. We can use the Go race detector to find race conditions and eliminate them.

**Comment by jstoja** [comment]
From my current tests the main colliding routines are:
- node.listen in node.go:77
- node.check in node.go:79
- node.manage in node.go:80

trying to concurrently access the node peers for example.

**Comment by awishformore** [comment]
Fixed in bb9f8e6409e19e1a2ddd1aa6f6fc8c002eaf7ad3, b46ed6b2da8f2fba168f538216a1c79a87063a4b, d678ad7f17507088213f3671afcea5558d6b2943.

**Comment by jasonv75** [comment]
bb9f8e6409e19e1a2ddd1aa6f6fc8c002eaf7ad3
b46ed6b2da8f2fba168f538216a1c79a87063a4b
bb9f8e6409e19e1a2ddd1aa6f6fc8c002eaf7ad3
